export const menuHighlights = [
  {
    name: "Paneer Tikka Roll",
    blurb: "Smoky paneer, green chutney, crisp veg.",
    price: "₹149",
    image: "/menu/paneer-tikka-roll.png",
    href: "#veg-rolls",
    grad: "from-amber/25 via-ember/10 to-crimson/20",
    imageClassName: "object-contain p-4 sm:p-5 scale-[1.05]",
  },
  {
    name: "Bubble Tea",
    blurb: "Chilled milk tea with chewy pearls.",
    price: "₹149",
    image: "/menu/bubble-tea.png",
    href: "#ice-tea",
    grad: "from-crimson/20 via-amber/10 to-bone/5",
    imageClassName: "object-contain p-6 sm:p-7 scale-[1.02]",
  },
  {
    name: "Virgin Mojito",
    blurb: "Crushed mint and lime over ice.",
    price: "₹119",
    image: "/menu/house-mojito.png",
    href: "#beverage",
    grad: "from-lime/20 via-amber/10 to-ember/10",
    imageClassName: "object-contain p-5 sm:p-6 scale-[1.02]",
  },
  {
    name: "Chicken Shawarma",
    blurb: "Charred chicken, salad, garlic cream.",
    price: "₹189",
    image: "/menu/chicken-shawarma.png",
    href: "#wraps-non-veg",
    grad: "from-ember/20 via-crimson/10 to-amber/20",
    imageClassName: "object-contain p-4 sm:p-5 scale-[1.08]",
  },
];

export const menuSections = [
  {
    id: "rolls",
    label: "Signature Rolls",
    title: "Freshly pressed. Properly loaded.",
    description:
      "The roll counter runs on griddled parathas, layered fillings, and big spice. Veg classics and non-veg heavy hitters both land here.",
    note: "Paratha options available: Royal Laccha Paratha or Multi Grain Paratha.",
    boardImage: "/menu/boards/rolls-board.png",
    groups: [
      {
        id: "veg-rolls",
        title: "Veg Rolls",
        badge: "Veg",
        accentClassName: "text-lime",
        image: "/menu/boards/veg-rolls-board.png",
        imageClassName: "object-cover object-center",
        items: [
          { name: "Mix Veg", prices: [{ amount: "₹99" }] },
          { name: "Spl Mix Veg", prices: [{ amount: "₹129" }] },
          { name: "Potato Masala Roll", prices: [{ amount: "₹99" }] },
          { name: "Veg Manchurian Roll", prices: [{ amount: "₹149" }] },
          { name: "Veg Kabab Tikki Roll", prices: [{ amount: "₹149" }] },
          { name: "Hara Bhara Kabab Roll", prices: [{ amount: "₹169" }] },
          { name: "Bhuna Soya Chaap Roll", prices: [{ amount: "₹159" }] },
          { name: "Soya Chaap Masala Roll", prices: [{ amount: "₹159" }] },
          { name: "Malai Soya Chaap Roll", prices: [{ amount: "₹179" }] },
          { name: "Paneer Classic Roll", prices: [{ amount: "₹169" }] },
          { name: "Veg Seek Kabab Roll", prices: [{ amount: "₹169" }] },
          { name: "Paneer Bhurji Roll", prices: [{ amount: "₹169" }] },
          { name: "Paneer Butter Masala Roll", prices: [{ amount: "₹199" }] },
          { name: "Chilli Paneer Roll", prices: [{ amount: "₹199" }] },
          { name: "Mushroom Roll", prices: [{ amount: "₹189" }] },
          { name: "Paneer Chatkara City Roll Spl", prices: [{ amount: "₹199" }] },
        ],
      },
      {
        id: "non-veg-rolls",
        title: "Non-Veg Rolls",
        badge: "Non-Veg",
        accentClassName: "text-crimson",
        image: "/menu/boards/non-veg-rolls-board.png",
        imageClassName: "object-cover object-center",
        note: "Second price reflects the egg-loaded version where listed.",
        items: [
          { name: "Egg Roll Single", prices: [{ label: "Classic", amount: "₹89" }, { label: "+Egg", amount: "₹99" }] },
          { name: "Chicken Manchurian Roll", prices: [{ label: "Classic", amount: "₹159" }, { label: "+Egg", amount: "₹179" }] },
          { name: "Chicken Roll", prices: [{ label: "Classic", amount: "₹159" }, { label: "+Egg", amount: "₹179" }] },
          { name: "Bhuna Chicken Roll", prices: [{ label: "Classic", amount: "₹169" }, { label: "+Egg", amount: "₹189" }] },
          { name: "Butter Chicken Roll", prices: [{ label: "Classic", amount: "₹189" }, { label: "+Egg", amount: "₹209" }] },
          { name: "Chicken Achari Roll", prices: [{ label: "Classic", amount: "₹199" }, { label: "+Egg", amount: "₹219" }] },
          { name: "Chicken Tikka Roll", prices: [{ label: "Classic", amount: "₹199" }, { label: "+Egg", amount: "₹219" }] },
          { name: "Chilli Chicken Roll", prices: [{ label: "Classic", amount: "₹199" }, { label: "+Egg", amount: "₹219" }] },
          { name: "Chicken Seek Kabab Roll", prices: [{ label: "Classic", amount: "₹169" }, { label: "+Egg", amount: "₹189" }] },
          { name: "Chicken Egg Keema Roll", prices: [{ label: "Classic", amount: "₹199" }, { label: "+Egg", amount: "₹219" }] },
          { name: "Chicken Shami Kabab Roll", prices: [{ label: "Classic", amount: "₹189" }, { label: "+Egg", amount: "₹209" }] },
          { name: "Mutton Seek Kabab Roll", prices: [{ label: "Classic", amount: "₹249" }, { label: "+Egg", amount: "₹269" }] },
          { name: "Mutton Shami Kabab Roll", prices: [{ label: "Classic", amount: "₹229" }, { label: "+Egg", amount: "₹249" }] },
          { name: "Mutton Egg Keema Roll", prices: [{ label: "Classic", amount: "₹249" }, { label: "+Egg", amount: "₹269" }] },
          { name: "Peri Peri Chicken Roll", prices: [{ label: "Classic", amount: "₹199" }, { label: "+Egg", amount: "₹219" }] },
          { name: "Crispy Chicken Roll", prices: [{ label: "Classic", amount: "₹199" }, { label: "+Egg", amount: "₹219" }] },
        ],
      },
    ],
  },
  {
    id: "burgers-snacks",
    label: "Burgers and Snacks",
    title: "Quick bites with real weight behind them.",
    description:
      "Burgers, fries, fingers, and kababs for the part of the order that needs crunch, heat, or a solid side.",
    note: "Snacks are listed exactly from the provided menu board.",
    boardImage: "/menu/boards/burgers-snacks-board.png",
    groups: [
      {
        id: "veg-burger",
        title: "Veg Burger",
        badge: "Veg",
        accentClassName: "text-lime",
        image: "/menu/boards/burgers-snacks-board.png",
        imageClassName: "object-cover object-left",
        items: [
          { name: "Veg Classic Burger", prices: [{ amount: "₹69" }] },
          { name: "Veg Cheese Burger", prices: [{ amount: "₹99" }] },
          { name: "Paneer Burger", prices: [{ amount: "₹129" }] },
          { name: "Double Tikki Burger", prices: [{ amount: "₹99" }] },
        ],
      },
      {
        id: "non-veg-burger",
        title: "Non-Veg Burger",
        badge: "Non-Veg",
        accentClassName: "text-crimson",
        image: "/menu/boards/burgers-snacks-board.png",
        imageClassName: "object-cover object-left",
        items: [
          { name: "Chicken Classic Burger", prices: [{ amount: "₹99" }] },
          { name: "Chicken Cheese Burger", prices: [{ amount: "₹129" }] },
          { name: "Crispy Chicken Burger", prices: [{ amount: "₹149" }] },
        ],
      },
      {
        id: "veg-snacks",
        title: "Veg Snacks",
        badge: "Snacks",
        accentClassName: "text-amber",
        image: "/menu/boards/burgers-snacks-board.png",
        imageClassName: "object-cover object-right",
        items: [
          { name: "French Fries", prices: [{ amount: "₹99" }] },
          { name: "Peri Peri French Fries", prices: [{ amount: "₹129" }] },
          { name: "Cheese Fingers 8 Pc.", prices: [{ amount: "₹169" }] },
          { name: "Potato Smiley", prices: [{ amount: "₹129" }] },
          { name: "Potato Wedges", prices: [{ amount: "₹139" }] },
          { name: "Cheese Fries", prices: [{ amount: "₹149" }] },
          { name: "Cheese French Fries", prices: [{ amount: "₹169" }] },
          { name: "Hara Bhara Kabab 6 Pc.", prices: [{ amount: "₹169" }] },
        ],
      },
      {
        id: "non-veg-snacks",
        title: "Non-Veg Snacks",
        badge: "Snacks",
        accentClassName: "text-amber",
        image: "/menu/boards/burgers-snacks-board.png",
        imageClassName: "object-cover object-right",
        items: [
          { name: "Chicken Seek Kabab 6 Pc.", prices: [{ amount: "₹199" }] },
          { name: "Mutton Seek Kabab 6 Pc.", prices: [{ amount: "₹249" }] },
          { name: "Chicken Popcorn", prices: [{ amount: "₹149" }] },
        ],
      },
    ],
  },
  {
    id: "beverages",
    label: "Drinks Counter",
    title: "Mojitos, coolers, coffee, and lassi.",
    description:
      "Cold pours, quick refreshers, and sweeter finishes. This section mirrors the full drinks lineup from the supplied menu.",
    note: "Tea, coffee, cold coffee, and lassi are all served from the same beverage counter.",
    boardImage: "/menu/boards/beverages-board.png",
    groups: [
      {
        id: "beverage",
        title: "Beverage",
        badge: "Cold",
        accentClassName: "text-amber",
        image: "/menu/boards/beverages-board.png",
        imageClassName: "object-cover object-left",
        items: [
          { name: "Fresh Lime Soda", prices: [{ amount: "₹99" }] },
          { name: "Masala Shikanji", prices: [{ amount: "₹99" }] },
          { name: "Mint Mojito", prices: [{ amount: "₹99" }] },
          { name: "Mango Mojito", prices: [{ amount: "₹119" }] },
          { name: "Orange Mojito", prices: [{ amount: "₹119" }] },
          { name: "Green Apple Mojito", prices: [{ amount: "₹119" }] },
          { name: "Watermelon Mojito", prices: [{ amount: "₹119" }] },
          { name: "Virgin Mojito", prices: [{ amount: "₹119" }] },
          { name: "Smoothie", prices: [{ amount: "₹149" }] },
          { name: "Kala Khatta", prices: [{ amount: "₹119" }] },
          { name: "Aam Panna", prices: [{ amount: "₹119" }] },
          { name: "Cold Drink Can", prices: [{ amount: "₹60" }] },
          { name: "Cold Drink Bottle", prices: [{ amount: "₹60" }] },
          { name: "Cold Drink @350ml", prices: [{ amount: "₹49" }] },
          { name: "Water Bottle", prices: [{ amount: "₹30" }] },
          { name: "Vedica Water Bottle", prices: [{ amount: "₹60" }] },
        ],
      },
      {
        id: "ice-tea",
        title: "Ice Tea",
        badge: "Tea",
        accentClassName: "text-amber",
        image: "/menu/bubble-tea.png",
        imageClassName: "object-contain p-6 sm:p-7",
        items: [
          { name: "Ice Tea", prices: [{ amount: "₹119" }] },
          { name: "Ice Lemon Tea", prices: [{ amount: "₹119" }] },
          { name: "Peach Tea", prices: [{ amount: "₹119" }] },
          { name: "Bubble Tea", prices: [{ amount: "₹149" }] },
        ],
      },
      {
        id: "hot-beverage",
        title: "Hot Beverage",
        badge: "Hot",
        accentClassName: "text-crimson",
        image: "/menu/boards/beverages-board.png",
        imageClassName: "object-cover object-right",
        items: [
          { name: "Hot Coffee", prices: [{ amount: "₹69" }] },
          { name: "Cappuccino Coffee", prices: [{ label: "Small", amount: "₹99" }, { label: "Large", amount: "₹149" }] },
          { name: "Hot Chocolate", prices: [{ amount: "₹149" }] },
          { name: "Black Coffee", prices: [{ amount: "₹69" }] },
        ],
      },
      {
        id: "cold-coffee",
        title: "Cold Coffee",
        badge: "Coffee",
        accentClassName: "text-bone",
        image: "/menu/boards/beverages-board.png",
        imageClassName: "object-cover object-right",
        items: [
          { name: "Classic Cold Coffee", prices: [{ amount: "₹139" }] },
          { name: "Hazelnut Cold Coffee", prices: [{ amount: "₹159" }] },
          { name: "Chocolate Cold Coffee", prices: [{ amount: "₹169" }] },
        ],
      },
      {
        id: "lassi",
        title: "Lassi",
        badge: "Sweet",
        accentClassName: "text-amber",
        image: "/menu/boards/beverages-board.png",
        imageClassName: "object-cover object-right",
        items: [
          { name: "Sweet Lassi", prices: [{ amount: "₹99" }] },
          { name: "Strawberry Lassi", prices: [{ amount: "₹129" }] },
          { name: "Mango Lassi", prices: [{ amount: "₹129" }] },
          { name: "Masala Lassi", prices: [{ amount: "₹99" }] },
          { name: "Masala Chaach", prices: [{ amount: "₹99" }] },
        ],
      },
    ],
  },
  {
    id: "wraps",
    label: "Wraps and Add-Ons",
    title: "Portable, loaded, and built for repeat orders.",
    description:
      "Wraps carry the heavier fillings, and add-ons let the final order move your way without overcomplicating the counter.",
    note: "Wraps are served with Royal Laccha Paratha or Multi Grain Paratha where applicable.",
    boardImage: "/menu/boards/wraps-board.png",
    groups: [
      {
        id: "wraps-veg",
        title: "Wraps Veg",
        badge: "Veg",
        accentClassName: "text-lime",
        image: "/menu/boards/wraps-board.png",
        imageClassName: "object-cover object-top",
        items: [
          { name: "Falafel Wraps", prices: [{ amount: "₹239" }] },
          { name: "Crispy Soya Wrap", prices: [{ amount: "₹239" }] },
          { name: "Paneer Bhurji Wrap", prices: [{ amount: "₹249" }] },
          { name: "Cheesy Paneer Bhurji Wrap", prices: [{ amount: "₹249" }] },
        ],
      },
      {
        id: "wraps-non-veg",
        title: "Wraps Non Veg",
        badge: "Non-Veg",
        accentClassName: "text-crimson",
        image: "/menu/chicken-shawarma.png",
        imageClassName: "object-contain p-4 sm:p-5 scale-[1.06]",
        items: [
          { name: "Roasted Chicken Wrap", prices: [{ amount: "₹249" }] },
          { name: "Shami Kabab Wrap", prices: [{ amount: "₹269" }] },
          { name: "Grilled Chicken Wrap", prices: [{ amount: "₹269" }] },
          { name: "Chicken Keema Wrap", prices: [{ amount: "₹279" }] },
        ],
      },
      {
        id: "add-ons",
        title: "Add On",
        badge: "Extras",
        accentClassName: "text-amber",
        image: "/menu/boards/wraps-board.png",
        imageClassName: "object-cover object-bottom",
        items: [
          { name: "Cheese", prices: [{ amount: "₹29" }] },
          { name: "Ice Cream", prices: [{ amount: "₹39" }] },
          { name: "Burger Tikki", prices: [{ amount: "₹29" }] },
          { name: "Egg", prices: [{ amount: "₹29" }] },
          { name: "Chicken", prices: [{ amount: "₹69" }] },
          { name: "Multi Grain", prices: [{ amount: "₹29" }] },
          { name: "Mayonnaise", prices: [{ amount: "₹39" }] },
        ],
      },
    ],
  },
];
